# Generated by Django 5.2.8 on 2025-11-16 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del emprendimiento')),
                ('categoria', models.CharField(choices=[('comida', 'Comida y Gastronomía'), ('agro', 'Agrícola / Huerta'), ('ropa', 'Ropa y Accesorios'), ('servicios', 'Servicios'), ('artesania', 'Artesanía'), ('otros', 'Otros')], default='otros', max_length=30, verbose_name='Categoría')),
                ('rubro', models.CharField(blank=True, max_length=100, verbose_name='Rubro / Tipo de negocio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de contacto')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, verbose_name='Correo de contacto')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web o redes sociales')),
                ('permite_agendar', models.BooleanField(default=False, verbose_name='Permite agendar horas')),
                ('permite_comprar', models.BooleanField(default=False, verbose_name='Permite compras online')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado por municipio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprendimientos', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Emprendimiento',
                'verbose_name_plural': 'Emprendimientos',
            },
        ),
    ]
