# Generated by Django 5.2.8 on 2025-11-19 00:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_producto_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprendimiento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveField(
            model_name='emprendimiento',
            name='permite_comprar',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='creada_en',
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='visitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida / Delivery'), ('ropa', 'Ropa / Boutique'), ('tienda', 'Tienda general'), ('alimentos', 'Alimentos'), ('servicio', 'Servicios (peluquería, uñas, etc.)'), ('otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprendimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='permite_agendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='rubro',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('menu', 'Plato / Menú (comida)'), ('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
    ]
