# Generated by Django 5.2.4 on 2025-11-29 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_reserva_estado_reserva_producto_reserva_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='permite_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emprendimiento',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida / Delivery'), ('ropa', 'Ropa / Boutique'), ('tienda', 'Tienda general'), ('alimentos', 'Alimentos'), ('servicios', 'Servicios (peluquería, uñas, etc.)'), ('otros', 'Otros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('menu', 'Plato / Menú'), ('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
    ]
