# Generated by Django 5.2.8 on 2025-11-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_remove_producto_imagen_url_emprendimiento_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='emprendimientos/'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='emprendimientos/'),
        ),
        migrations.AddField(
            model_name='emprendimiento',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='emprendimientos/'),
        ),
    ]
